services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5556:5556"
    volumes:
      - .:/app
      - ./database:/app/database
    environment:
      - FLASK_ENV=development
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=db
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  mysql_data:
